name = ""
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "sparrow"
database_id = ""

[vars]
AUTH_TOKEN = ""
DISCORD_WEBHOOK = "https://discord.com/api/webhooks/"

[triggers]
crons = ["0 1 * * *"]